layout_spectrum: 0.2838984
typography_spectrum: 0.9893498
color:
  saturation: 0.7013285
  lightness: 0.7466834
  brandStrength: 0.6494004
  rhythmicContrast: 0.2098189
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Shavonga
